/**
 * Printable QR code for asking a customer for a review face to face.
 *
 * The code encodes the web app's review gate URL for one review_requests row,
 * so it has to be handed a real row id (see lib/review-requests.ts — the id is
 * generated by the database and returned by `.select('id')`).
 *
 * Two things this screen will refuse to do, because a wrong QR code is worse
 * than none:
 *   1. Render anything when EXPO_PUBLIC_APP_URL is unset. The old link helper
 *      fell back to a hardcoded domain; printing that onto a sticker sends
 *      customers to a site this install does not control.
 *   2. Pretend a demo id works. Local ids never resolve on the web gate, so the
 *      code is shown behind an explicit "won't scan to a live page" banner.
 *
 * The card is white in both themes on purpose: scanners need dark-on-light, and
 * a dark-mode QR is unreadable to most phone cameras.
 */

import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import { Redirect, useLocalSearchParams } from 'expo-router';
import * as Sharing from 'expo-sharing';
import React, { useRef, useState } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import ViewShot, { captureRef } from 'react-native-view-shot';

import { Button, Card, IconTile } from '@/components/ui/basics';
import { DetailHeader, Screen, Section } from '@/components/ui/screen';
import { Radius, Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { useWorkspace } from '@/hooks/use-workspace';
import { notify } from '@/lib/format';
import { reviewUrl } from '@/lib/review-requests';
import { useAuth } from '@/providers/auth-provider';

const CARD_QR_SIZE = 208;

function esc(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export default function ReviewQrScreen() {
  const { colors } = useTheme();
  const { user, initializing } = useAuth();
  const { business } = useWorkspace();
  const params = useLocalSearchParams<{
    id?: string;
    name?: string;
    job?: string;
    /** '1' when the id only exists on this device (demo mode). */
    local?: string;
    /** '1' when the row was created without a business_id. */
    unbranded?: string;
  }>();

  const requestId = params.id ?? '';
  const customerName = params.name?.trim() ?? '';
  const jobTitle = params.job?.trim() ?? '';
  const isLocalId = params.local === '1';
  const isUnbranded = params.unbranded === '1';

  const [working, setWorking] = useState<'share' | 'print' | null>(null);
  const shotRef = useRef<View>(null);

  if (!initializing && !user) {
    return <Redirect href="/login" />;
  }

  const url = requestId ? reviewUrl(requestId) : null;
  const businessName = business?.name ?? '';

  /** Renders the white card to a JPEG file. Native only; web never calls it. */
  const capture = async (): Promise<{ uri: string; base64: string } | null> => {
    const uri = await captureRef(shotRef, {
      format: 'jpg',
      quality: 0.95,
      result: 'tmpfile',
      width: 1200,
    });
    const base64 = await FileSystem.readAsStringAsync(uri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    return { uri, base64 };
  };

  const handleShare = async () => {
    if (working) return;
    setWorking('share');
    try {
      const shot = await capture();
      if (shot && (await Sharing.isAvailableAsync())) {
        await Sharing.shareAsync(shot.uri, {
          mimeType: 'image/jpeg',
          dialogTitle: 'Review QR code',
          UTI: 'public.jpeg',
        });
      }
    } catch (error) {
      notify('Could not share', error instanceof Error ? error.message : 'Try again.');
    } finally {
      setWorking(null);
    }
  };

  const handlePrint = async () => {
    if (working || !url) return;
    setWorking('print');
    try {
      // The printed sheet is the captured card, so the paper matches what the
      // customer saw on screen.
      const shot = await capture();
      if (!shot) return;
      const body = `<img class="card" src="data:image/jpeg;base64,${shot.base64}" />`;
      const heading = [businessName, jobTitle].filter(Boolean).join(' · ');
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0;
                 padding: 48px; text-align: center; color: #111827; background: #ffffff; }
          h1 { font-size: 22px; margin: 0 0 4px; }
          .sub { font-size: 13px; color: #6b7280; margin: 0 0 28px; }
          img.card { width: 360px; max-width: 100%; border: 1px solid #e5e7eb; border-radius: 12px; }
          .url { margin-top: 24px; font-size: 12px; color: #6b7280; word-break: break-all; }
        </style></head><body>
        <h1>Scan to leave us a review</h1>
        <p class="sub">${esc(heading || 'Thanks for your business!')}</p>
        ${body}
        <p class="url">${esc(url)}</p>
        </body></html>`;

      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Review QR code',
          UTI: 'com.adobe.pdf',
        });
      }
    } catch (error) {
      notify('Could not print', error instanceof Error ? error.message : 'Try again.');
    } finally {
      setWorking(null);
    }
  };

  const handleCopy = async () => {
    if (!url) return;
    await Clipboard.setStringAsync(url);
    notify('Link copied', 'Paste it into a text, an email or your invoice template.');
  };

  return (
    <Screen>
      <DetailHeader title="Review QR code" />

      {!requestId ? (
        <Card>
          <Text style={{ color: colors.textSecondary, fontSize: 14 }}>
            No review request was passed to this screen, so there is nothing to encode.
          </Text>
        </Card>
      ) : !url ? (
        <Card style={{ alignItems: 'center', gap: Spacing.md }}>
          <IconTile icon="link-outline" tone="danger" />
          <Text style={{ fontSize: 15, fontWeight: '700', color: colors.text, textAlign: 'center' }}>
            No review link to encode
          </Text>
          <Text style={{ fontSize: 13.5, color: colors.textSecondary, textAlign: 'center' }}>
            EXPO_PUBLIC_APP_URL is not set to your deployed web app, so this build has no address
            for the review page. A QR code is not shown rather than printing one that points
            somewhere you don&apos;t control. Set it (for example https://reviews.yourcompany.com)
            and rebuild.
          </Text>
        </Card>
      ) : (
        <>
          {isLocalId ? (
            <Card style={{ flexDirection: 'row', gap: Spacing.md, alignItems: 'flex-start' }}>
              <Ionicons name="flask-outline" size={18} color={colors.warningStrong} />
              <Text style={{ flex: 1, fontSize: 13, color: colors.textSecondary, lineHeight: 19 }}>
                Demo mode — this request only exists on this phone, so the code below scans to a
                page that can&apos;t find it. It&apos;s here to show the layout. Connect Supabase to
                hand out codes that work.
              </Text>
            </Card>
          ) : isUnbranded ? (
            <Card style={{ flexDirection: 'row', gap: Spacing.md, alignItems: 'flex-start' }}>
              <Ionicons name="alert-circle-outline" size={18} color={colors.warningStrong} />
              <Text style={{ flex: 1, fontSize: 13, color: colors.textSecondary, lineHeight: 19 }}>
                This request was saved without a business link, so the review page may not show your
                name and logo. The database is missing the business_id column.
              </Text>
            </Card>
          ) : null}

          <Section title="Show this to your customer">
            {/* White, always: QR scanners need dark-on-light and a dark-mode
                code fails to read on most phone cameras. */}
            <ViewShot ref={shotRef} style={styles.shot}>
              <Text style={styles.cardHeading}>Scan to leave us a review</Text>
              {businessName ? <Text style={styles.cardBusiness}>{businessName}</Text> : null}
              <View style={styles.qrWrap}>
                <QRCode
                  value={url}
                  size={CARD_QR_SIZE}
                  color="#000000"
                  backgroundColor="#FFFFFF"
                  ecl="M"
                />
              </View>
              <Text style={styles.cardFooter}>
                {customerName ? `Thanks, ${customerName}!` : 'Thanks for your business!'}
                {jobTitle ? ` · ${jobTitle}` : ''}
              </Text>
            </ViewShot>
          </Section>

          <Card style={{ gap: 6 }}>
            <Text style={{ fontSize: 12.5, fontWeight: '600', color: colors.textSecondary }}>
              Review link
            </Text>
            <Text selectable style={{ fontSize: 13, color: colors.text }}>
              {url}
            </Text>
          </Card>

          {/* Share and print both go through react-native-view-shot, which has
              no web implementation — rather than a button that quietly does
              nothing, web gets the copy action and its own printing route. */}
          {Platform.OS === 'web' ? null : (
            <View style={{ flexDirection: 'row', gap: Spacing.md }}>
              <Button
                label="Share"
                icon="share-outline"
                variant="secondary"
                style={{ flex: 1 }}
                loading={working === 'share'}
                onPress={() => void handleShare()}
              />
              <Button
                label="Print"
                icon="print-outline"
                variant="secondary"
                style={{ flex: 1 }}
                loading={working === 'print'}
                onPress={() => void handlePrint()}
              />
            </View>
          )}
          <Button
            label="Copy link"
            icon="copy-outline"
            variant="secondary"
            onPress={() => void handleCopy()}
          />
          <Text style={{ fontSize: 12, color: colors.textMuted, textAlign: 'center' }}>
            {Platform.OS === 'web'
              ? 'Use your browser’s print (Ctrl/Cmd + P) to print this page. Sharing and saving the code as an image work on your phone (iOS/Android).'
              : 'Save the image from the share sheet to stick it on an invoice, a van or the counter.'}
          </Text>
        </>
      )}
    </Screen>
  );
}

const styles = StyleSheet.create({
  shot: {
    backgroundColor: '#FFFFFF',
    borderRadius: Radius.lg,
    paddingVertical: Spacing.xxl,
    paddingHorizontal: Spacing.lg,
    alignItems: 'center',
    gap: Spacing.sm,
  },
  cardHeading: {
    fontSize: 17,
    fontWeight: '800',
    color: '#111827',
    textAlign: 'center',
  },
  cardBusiness: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
  },
  qrWrap: {
    backgroundColor: '#FFFFFF',
    padding: Spacing.md,
    marginTop: Spacing.xs,
  },
  cardFooter: {
    fontSize: 12.5,
    color: '#6B7280',
    textAlign: 'center',
  },
});
