import React, { useState, useRef, useCallback, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { SmartDropdownInput } from "@/components/SmartDropdownInput";
import { DROPDOWN_FIELDS } from "@/hooks/useDropdownState";
import {
  Upload,
  X,
  Tag,
  Image,
  Video,
  File,
  Check,
  AlertCircle,
  Plus,
  FolderOpen,
  Eye,
  Trash2,
  RotateCcw,
  Wand2,
  Globe,
  Hash,
  FileText,
  User,
  Calendar,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import {
  SecureMediaUrlGenerator,
  type SecureMediaFile,
} from "@/lib/secureMediaUrls";

interface FileWithMetadata {
  id: string;
  file: File;
  preview?: string;
  // Core metadata fields
  title: string;
  description: string;
  tags: string;
  keywords: string;
  altText: string;
  category: string;
  // Enhanced metadata fields
  fileName: string;
  attribution: string;
  caption: string;
  exifData?: {
    camera?: string;
    lens?: string;
    focalLength?: string;
    aperture?: string;
    shutterSpeed?: string;
    iso?: string;
    dateTaken?: string;
    gpsCoordinates?: string;
    [key: string]: any;
  };
  structuredData?: {
    "@context"?: string;
    "@type"?: string;
    name?: string;
    description?: string;
    creator?: string;
    dateCreated?: string;
    contentUrl?: string;
    license?: string;
    [key: string]: any;
  };
  // Technical fields (auto-populated)
  status: "pending" | "processing" | "ready" | "error";
  error?: string;
  autoGenerated?: {
    slug?: string;
    aiDescription?: string;
    suggestedTags?: string[];
    suggestedKeywords?: string[];
    extractedExif?: any;
  };
  // Secure URL integration
  secureMediaFile?: SecureMediaFile;
}

interface SmartMediaUploaderProps {
  onFilesReady: (files: FileWithMetadata[]) => void;
  acceptedTypes?: string[];
  maxFiles?: number;
  maxFileSize?: number; // in MB
  projectInfo?: {
    name: string;
    keywords: string[];
    address?: string;
    customerName?: string;
    id?: string;
  };
  // Settings from admin panel
  enableAIFeatures?: boolean;
  autoApplyDefaults?: boolean;
  className?: string;
  // Context for URL generation
  context?: {
    type: "project" | "gallery";
    projectId?: string;
    isPublic?: boolean;
  };
}

export function SmartMediaUploader({
  onFilesReady,
  acceptedTypes = ["image/*", "video/*"],
  maxFiles = 20,
  maxFileSize = 100,
  projectInfo,
  enableAIFeatures = true,
  autoApplyDefaults = true,
  className,
  context = { type: "project", isPublic: true },
}: SmartMediaUploaderProps) {
  const [files, setFiles] = useState<FileWithMetadata[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [editMode, setEditMode] = useState<"simple" | "advanced" | "complete">(
    "simple",
  );
  const [bulkEdit, setBulkEdit] = useState(false);
  const [bulkMetadata, setBulkMetadata] = useState({
    category: "",
    tags: "",
    keywords: "",
    attribution: "",
    caption: "",
  });
  const fileInputRef = useRef<HTMLInputElement>(null);
  const dragCounterRef = useRef(0);

  // Generate preview for files
  const generatePreview = useCallback((file: File): Promise<string | null> => {
    return new Promise((resolve) => {
      if (file.type.startsWith("image/")) {
        const reader = new FileReader();
        reader.onload = (e) => resolve(e.target?.result as string);
        reader.onerror = () => resolve(null);
        reader.readAsDataURL(file);
      } else if (file.type.startsWith("video/")) {
        const video = document.createElement("video");
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");

        video.addEventListener("loadedmetadata", () => {
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          video.currentTime = 1;
        });

        video.addEventListener("seeked", () => {
          if (ctx) {
            ctx.drawImage(video, 0, 0);
            resolve(canvas.toDataURL());
          } else {
            resolve(null);
          }
        });

        video.src = URL.createObjectURL(file);
      } else {
        resolve(null);
      }
    });
  }, []);

  // Extract EXIF data from image files
  const extractExifData = useCallback(async (file: File): Promise<any> => {
    if (!file.type.startsWith("image/")) {
      return null;
    }

    try {
      // Basic EXIF extraction using FileReader and manual parsing
      return new Promise((resolve) => {
        const reader = new FileReader();
        reader.onload = (e) => {
          const arrayBuffer = e.target?.result as ArrayBuffer;
          if (!arrayBuffer) {
            resolve(null);
            return;
          }

          // Simple EXIF extraction - in production, use a library like 'exifr' or 'piexifjs'
          const dataView = new DataView(arrayBuffer);
          const exifData: any = {
            fileSize: file.size,
            fileName: file.name,
            mimeType: file.type,
            lastModified: new Date(file.lastModified).toISOString(),
          };

          // Basic image dimensions extraction
          if (file.type === "image/jpeg") {
            // JPEG EXIF parsing would go here
            exifData.format = "JPEG";
          } else if (file.type === "image/png") {
            exifData.format = "PNG";
          }

          // Placeholder for actual EXIF data - in production, implement proper parsing
          exifData.camera = "Unknown";
          exifData.dateTaken = new Date(file.lastModified).toISOString();

          resolve(exifData);
        };
        reader.onerror = () => resolve(null);
        reader.readAsArrayBuffer(file);
      });
    } catch (error) {
      console.error("Error extracting EXIF data:", error);
      return null;
    }
  }, []);

  // Auto-generate metadata
  const generateMetadata = useCallback(
    (file: File): Partial<FileWithMetadata> => {
      const title = file.name.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " ");
      const slug = title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, "")
        .replace(/\s+/g, "-");

      // Auto-suggest based on project info
      const projectTags = projectInfo?.keywords || [];
      const suggestedTags = [];

      // Add project-based suggestions
      if (projectInfo?.name) {
        if (projectInfo.name.toLowerCase().includes("kitchen"))
          suggestedTags.push("kitchen", "renovation", "interior");
        if (projectInfo.name.toLowerCase().includes("bathroom"))
          suggestedTags.push("bathroom", "renovation", "plumbing");
        if (projectInfo.name.toLowerCase().includes("exterior"))
          suggestedTags.push("exterior", "landscaping", "outdoor");
      }

      // Add file type suggestions
      if (file.type.startsWith("image/")) {
        suggestedTags.push("photo", "before", "progress");
      } else if (file.type.startsWith("video/")) {
        suggestedTags.push("video", "walkthrough", "demonstration");
      }

      return {
        title,
        fileName: file.name,
        description: autoApplyDefaults
          ? `${projectInfo?.name || "Project"} - ${title}`
          : "",
        tags: autoApplyDefaults ? projectTags.join(", ") : "",
        keywords: autoApplyDefaults
          ? [...projectTags, ...suggestedTags].join(", ")
          : "",
        altText: autoApplyDefaults
          ? `${title} - ${projectInfo?.name || "Project"} photo`
          : "",
        category: autoApplyDefaults ? "project-media" : "",
        attribution: autoApplyDefaults
          ? `${projectInfo?.customerName || "Unknown"} - ${projectInfo?.name || "Project"}`
          : "",
        caption: autoApplyDefaults
          ? `${title} from ${projectInfo?.name || "Project"}`
          : "",
        structuredData: autoApplyDefaults
          ? {
              "@context": "https://schema.org",
              "@type": file.type.startsWith("image/")
                ? "ImageObject"
                : "VideoObject",
              name: title,
              description: `${projectInfo?.name || "Project"} - ${title}`,
              creator: projectInfo?.customerName || "Unknown",
              dateCreated: new Date().toISOString(),
              contentUrl: "", // Will be filled when URL is generated
            }
          : undefined,
        autoGenerated: {
          slug,
          suggestedTags,
          suggestedKeywords: [...projectTags, ...suggestedTags],
        },
      };
    },
    [projectInfo, autoApplyDefaults],
  );

  // Validate file
  const validateFile = useCallback(
    (file: File): { valid: boolean; error?: string } => {
      const isValidType = acceptedTypes.some((type) => {
        if (type.endsWith("/*")) {
          return file.type.startsWith(type.slice(0, -1));
        }
        return file.type === type;
      });

      if (!isValidType) {
        return {
          valid: false,
          error: `File type not supported. Accepted: ${acceptedTypes.join(", ")}`,
        };
      }

      const fileSizeMB = file.size / (1024 * 1024);
      if (fileSizeMB > maxFileSize) {
        return {
          valid: false,
          error: `File too large. Maximum size: ${maxFileSize}MB`,
        };
      }

      return { valid: true };
    },
    [acceptedTypes, maxFileSize],
  );

  // Process files
  const processFiles = useCallback(
    async (fileList: FileList | File[]) => {
      const newFiles: FileWithMetadata[] = [];
      const filesArray = Array.from(fileList);

      if (files.length + filesArray.length > maxFiles) {
        toast.error(`Maximum ${maxFiles} files allowed`);
        return;
      }

      for (const file of filesArray) {
        const validation = validateFile(file);
        const id = `file-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        const metadata = generateMetadata(file);

        if (!validation.valid) {
          newFiles.push({
            id,
            file,
            ...metadata,
            title: file.name,
            description: "",
            tags: "",
            keywords: "",
            altText: "",
            category: "",
            status: "error",
            error: validation.error,
          } as FileWithMetadata);
          continue;
        }

        const fileData: FileWithMetadata = {
          id,
          file,
          status: "processing",
          ...metadata,
        } as FileWithMetadata;

        newFiles.push(fileData);

        // Generate preview, extract EXIF, secure URLs, and AI metadata asynchronously
        Promise.all([generatePreview(file), extractExifData(file)]).then(
          async ([preview, exifData]) => {
            let aiMetadata = {};

            // Simulate AI processing if enabled
            if (enableAIFeatures && file.type.startsWith("image/")) {
              // Simulate AI alt text generation
              await new Promise((resolve) => setTimeout(resolve, 1000));
              aiMetadata = {
                aiDescription: `AI-generated description for ${metadata.title}`,
                extractedExif: exifData,
              };
            }

            // Generate secure URLs
            const contextWithProject = {
              ...context,
              projectId: projectInfo?.id || context.projectId,
            };
            const secureMediaFile =
              SecureMediaUrlGenerator.generateContextualUrls(
                file,
                contextWithProject,
                metadata,
              );

            setFiles((prev) =>
              prev.map((f) =>
                f.id === id
                  ? {
                      ...f,
                      preview: preview || undefined,
                      status: "ready",
                      exifData: exifData,
                      autoGenerated: { ...f.autoGenerated, ...aiMetadata },
                      secureMediaFile,
                    }
                  : f,
              ),
            );
          },
        );
      }

      setFiles((prev) => [...prev, ...newFiles]);
      toast.success(`Added ${filesArray.length} file(s)`);
    },
    [
      files.length,
      maxFiles,
      validateFile,
      generateMetadata,
      generatePreview,
      extractExifData,
      enableAIFeatures,
    ],
  );

  // Drag and drop handlers
  const handleDragEnter = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounterRef.current++;
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounterRef.current--;
    if (dragCounterRef.current === 0) {
      setIsDragging(false);
    }
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setIsDragging(false);
      dragCounterRef.current = 0;

      const droppedFiles = e.dataTransfer.files;
      if (droppedFiles.length > 0) {
        processFiles(droppedFiles);
      }
    },
    [processFiles],
  );

  // File input handler
  const handleFileInput = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const selectedFiles = e.target.files;
      if (selectedFiles && selectedFiles.length > 0) {
        processFiles(selectedFiles);
      }
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    },
    [processFiles],
  );

  // Update file metadata
  const updateFile = useCallback(
    (
      id: string,
      updates: Partial<
        Pick<
          FileWithMetadata,
          | "title"
          | "fileName"
          | "tags"
          | "description"
          | "keywords"
          | "altText"
          | "category"
          | "attribution"
          | "caption"
          | "exifData"
          | "structuredData"
        >
      >,
    ) => {
      setFiles((prev) =>
        prev.map((file) => (file.id === id ? { ...file, ...updates } : file)),
      );
    },
    [],
  );

  // Apply bulk metadata
  const applyBulkMetadata = useCallback(() => {
    const readyFiles = files.filter((f) => f.status === "ready");
    readyFiles.forEach((file) => {
      const updates: any = {};
      if (bulkMetadata.category) updates.category = bulkMetadata.category;
      if (bulkMetadata.tags) {
        updates.tags = file.tags
          ? `${file.tags}, ${bulkMetadata.tags}`
          : bulkMetadata.tags;
      }
      if (bulkMetadata.keywords) {
        updates.keywords = file.keywords
          ? `${file.keywords}, ${bulkMetadata.keywords}`
          : bulkMetadata.keywords;
      }
      if (bulkMetadata.attribution) {
        updates.attribution = bulkMetadata.attribution;
      }
      if (bulkMetadata.caption) {
        updates.caption = bulkMetadata.caption;
      }
      updateFile(file.id, updates);
    });
    setBulkEdit(false);
    setBulkMetadata({
      category: "",
      tags: "",
      keywords: "",
      attribution: "",
      caption: "",
    });
    toast.success("Bulk metadata applied to all files");
  }, [files, bulkMetadata, updateFile]);

  // Apply AI suggestions
  const applyAISuggestions = useCallback(
    (fileId: string) => {
      const file = files.find((f) => f.id === fileId);
      if (!file?.autoGenerated) return;

      const updates: any = {};
      if (file.autoGenerated.aiDescription) {
        updates.altText = file.autoGenerated.aiDescription;
      }
      if (file.autoGenerated.suggestedTags?.length) {
        updates.tags = file.autoGenerated.suggestedTags.join(", ");
      }
      if (file.autoGenerated.suggestedKeywords?.length) {
        updates.keywords = file.autoGenerated.suggestedKeywords.join(", ");
      }

      updateFile(fileId, updates);
      toast.success("AI suggestions applied");
    },
    [files, updateFile],
  );

  // Remove file
  const removeFile = useCallback((id: string) => {
    setFiles((prev) => prev.filter((file) => file.id !== id));
  }, []);

  // Get file icon
  const getFileIcon = useCallback((file: File) => {
    if (file.type.startsWith("image/")) {
      return <Image className="h-4 w-4" />;
    } else if (file.type.startsWith("video/")) {
      return <Video className="h-4 w-4" />;
    }
    return <File className="h-4 w-4" />;
  }, []);

  // Format file size
  const formatFileSize = useCallback((bytes: number) => {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
  }, []);

  // Handle upload completion
  const handleUpload = useCallback(() => {
    const readyFiles = files.filter((f) => f.status === "ready");
    if (readyFiles.length === 0) {
      toast.error("No files ready for upload");
      return;
    }

    onFilesReady(readyFiles);
    setFiles([]);
  }, [files, onFilesReady]);

  const readyFilesCount = files.filter((f) => f.status === "ready").length;
  const errorFilesCount = files.filter((f) => f.status === "error").length;

  return (
    <div className={cn("space-y-4", className)}>
      {/* Drop Zone */}
      <Card
        className={cn(
          "border-2 border-dashed transition-all duration-200 cursor-pointer",
          isDragging
            ? "border-primary bg-primary/5 scale-[1.02]"
            : "border-muted-foreground/25 hover:border-primary/50 hover:bg-muted/30",
          files.length > 0 && "border-solid border-border",
        )}
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
      >
        <CardContent className="p-8 text-center">
          {isDragging ? (
            <div className="space-y-2">
              <Upload className="h-12 w-12 mx-auto text-primary animate-bounce" />
              <p className="text-lg font-medium text-primary">
                Drop files here to upload
              </p>
            </div>
          ) : files.length === 0 ? (
            <div className="space-y-4">
              <div className="space-y-2">
                <Upload className="h-12 w-12 mx-auto text-muted-foreground" />
                <h3 className="text-lg font-semibold">Upload Media Files</h3>
                <p className="text-muted-foreground">
                  Drag and drop files here or click to browse
                </p>
              </div>
              {projectInfo && (
                <div className="text-sm text-muted-foreground bg-blue-50 p-3 rounded-lg">
                  <p className="font-medium text-blue-900 mb-1">
                    📂 Uploading to: {projectInfo.name}
                  </p>
                  <p>Default tags and metadata will be applied automatically</p>
                </div>
              )}
              <Button className="gap-2">
                <FolderOpen className="h-4 w-4" />
                Choose Files
              </Button>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="flex items-center justify-center gap-2">
                <Upload className="h-6 w-6 text-muted-foreground" />
                <span className="font-medium">
                  {files.length} file{files.length !== 1 ? "s" : ""} selected
                </span>
              </div>
              <div className="flex justify-center gap-4 text-sm">
                {readyFilesCount > 0 && (
                  <span className="text-green-600 flex items-center gap-1">
                    <Check className="h-3 w-3" />
                    {readyFilesCount} ready
                  </span>
                )}
                {errorFilesCount > 0 && (
                  <span className="text-red-600 flex items-center gap-1">
                    <AlertCircle className="h-3 w-3" />
                    {errorFilesCount} error{errorFilesCount !== 1 ? "s" : ""}
                  </span>
                )}
              </div>
              <Button variant="outline" className="gap-2">
                <Plus className="h-4 w-4" />
                Add More Files
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Hidden file input */}
      <input
        ref={fileInputRef}
        type="file"
        multiple
        accept={acceptedTypes.join(",")}
        onChange={handleFileInput}
        className="hidden"
      />

      {/* File Management */}
      {files.length > 0 && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                <Tag className="h-5 w-5" />
                Media Files & Metadata
              </CardTitle>
              <div className="flex gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-sm text-muted-foreground">Mode:</span>
                  <Select
                    value={editMode}
                    onValueChange={(value) =>
                      setEditMode(value as "simple" | "advanced" | "complete")
                    }
                  >
                    <SelectTrigger className="w-36 h-10 md:h-8">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="simple">Simple</SelectItem>
                      <SelectItem value="advanced">Advanced</SelectItem>
                      <SelectItem value="complete">Complete</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setBulkEdit(!bulkEdit)}
                  className="gap-2"
                >
                  <Hash className="h-3 w-3" />
                  Bulk Edit
                </Button>
                <Button
                  size="sm"
                  onClick={handleUpload}
                  disabled={readyFilesCount === 0}
                  className="gap-2"
                >
                  <Upload className="h-3 w-3" />
                  Upload {readyFilesCount} File
                  {readyFilesCount !== 1 ? "s" : ""}
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            {/* Bulk Edit Panel */}
            {bulkEdit && (
              <Card className="mb-4 bg-blue-50 border-blue-200">
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-3">
                    <h4 className="font-semibold text-blue-900">
                      Apply to All Files
                    </h4>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setBulkEdit(false)}
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  </div>
                  <div className="space-y-3 mb-3">
                    <div className="grid grid-cols-1 gap-3">
                      <div>
                        <Label className="text-xs">Category</Label>
                        <Input
                          placeholder="e.g., progress photos"
                          value={bulkMetadata.category}
                          onChange={(e) =>
                            setBulkMetadata((prev) => ({
                              ...prev,
                              category: e.target.value,
                            }))
                          }
                          className="h-8"
                        />
                      </div>
                      <div>
                        <Label className="text-xs">Additional Tags</Label>
                        <SmartDropdownInput
                          fieldName={DROPDOWN_FIELDS.PROJECT_KEYWORDS}
                          value={bulkMetadata.tags}
                          onChange={(value) =>
                            setBulkMetadata((prev) => ({
                              ...prev,
                              tags: value,
                            }))
                          }
                          placeholder="before, progress, final"
                          allowMultiple={true}
                          separator=","
                          className="h-8"
                        />
                      </div>
                      <div>
                        <Label className="text-xs">Additional Keywords</Label>
                        <Input
                          placeholder="renovation, construction"
                          value={bulkMetadata.keywords}
                          onChange={(e) =>
                            setBulkMetadata((prev) => ({
                              ...prev,
                              keywords: e.target.value,
                            }))
                          }
                          className="h-8"
                        />
                      </div>
                    </div>
                    <div className="grid grid-cols-1 gap-3">
                      <div>
                        <Label className="text-xs">Attribution</Label>
                        <Input
                          placeholder="Photo credit or copyright"
                          value={bulkMetadata.attribution}
                          onChange={(e) =>
                            setBulkMetadata((prev) => ({
                              ...prev,
                              attribution: e.target.value,
                            }))
                          }
                          className="h-8"
                        />
                      </div>
                      <div>
                        <Label className="text-xs">Caption Template</Label>
                        <Input
                          placeholder="Standard caption for all files"
                          value={bulkMetadata.caption}
                          onChange={(e) =>
                            setBulkMetadata((prev) => ({
                              ...prev,
                              caption: e.target.value,
                            }))
                          }
                          className="h-8"
                        />
                      </div>
                    </div>
                  </div>
                  <Button
                    onClick={applyBulkMetadata}
                    size="sm"
                    className="gap-2"
                  >
                    <Check className="h-3 w-3" />
                    Apply to All Files
                  </Button>
                </CardContent>
              </Card>
            )}

            {/* File List */}
            <div className="space-y-3">
              {files.map((file) => (
                <Card
                  key={file.id}
                  className={cn(
                    "border-l-4",
                    file.status === "ready" && "border-l-green-500",
                    file.status === "error" && "border-l-red-500",
                    file.status === "processing" && "border-l-yellow-500",
                  )}
                >
                  <CardContent className="p-4">
                    <div className="flex gap-3">
                      {/* Preview */}
                      <div className="flex-shrink-0">
                        {file.preview ? (
                          <div className="relative w-16 h-16 rounded-lg overflow-hidden bg-muted">
                            <img
                              src={file.preview}
                              alt={file.title}
                              className="w-full h-full object-cover"
                            />
                          </div>
                        ) : (
                          <div className="w-16 h-16 rounded-lg flex items-center justify-center bg-muted">
                            {getFileIcon(file.file)}
                          </div>
                        )}
                      </div>

                      {/* File Info & Metadata */}
                      <div className="flex-1 min-w-0 space-y-3">
                        {/* Header */}
                        <div className="flex items-start justify-between gap-2">
                          <div className="min-w-0">
                            <div className="flex items-center gap-2 text-xs text-muted-foreground">
                              <span>{formatFileSize(file.file.size)}</span>
                              <span>•</span>
                              <span>{file.file.type}</span>
                              {file.status === "processing" && (
                                <>
                                  <span>•</span>
                                  <span className="text-yellow-600">
                                    Processing...
                                  </span>
                                </>
                              )}
                            </div>
                          </div>
                          <div className="flex gap-1">
                            {enableAIFeatures && file.autoGenerated && (
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => applyAISuggestions(file.id)}
                                className="h-6 w-6 p-0 text-blue-600"
                                title="Apply AI suggestions"
                              >
                                <Wand2 className="h-3 w-3" />
                              </Button>
                            )}
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => removeFile(file.id)}
                              className="h-6 w-6 p-0 text-red-600 hover:text-red-700 hover:bg-red-50"
                            >
                              <Trash2 className="h-3 w-3" />
                            </Button>
                          </div>
                        </div>

                        {file.status === "error" && file.error && (
                          <div className="text-xs text-red-600 bg-red-50 p-2 rounded">
                            {file.error}
                          </div>
                        )}

                        {/* Metadata Fields */}
                        <div className="space-y-3">
                          {/* Title (Always visible) */}
                          <div>
                            <Label className="text-xs font-medium">Title</Label>
                            <Input
                              value={file.title}
                              onChange={(e) =>
                                updateFile(file.id, { title: e.target.value })
                              }
                              placeholder="Enter a descriptive title..."
                              className="h-10 md:h-8 text-base md:text-sm"
                            />
                          </div>

                          {/* Simple Mode - Essential Fields */}
                          {editMode === "simple" && (
                            <div className="space-y-3">
                              {/* Caption */}
                              <div>
                                <Label className="text-xs font-medium">
                                  Caption
                                </Label>
                                <Input
                                  value={file.caption}
                                  onChange={(e) =>
                                    updateFile(file.id, {
                                      caption: e.target.value,
                                    })
                                  }
                                  placeholder="Short caption for this media..."
                                  className="h-10 md:h-8 text-base md:text-sm"
                                />
                              </div>

                              {/* Tags and Category Grid */}
                              <div className="grid grid-cols-1 gap-3">
                                <div>
                                  <Label className="text-xs font-medium">
                                    Tags
                                  </Label>
                                  <SmartDropdownInput
                                    fieldName={DROPDOWN_FIELDS.PROJECT_KEYWORDS}
                                    value={file.tags}
                                    onChange={(value) =>
                                      updateFile(file.id, { tags: value })
                                    }
                                    placeholder="kitchen, before, progress"
                                    allowMultiple={true}
                                    separator=","
                                    className="h-10 md:h-8 text-base md:text-sm"
                                  />
                                </div>
                                <div>
                                  <Label className="text-xs font-medium">
                                    Category
                                  </Label>
                                  <Select
                                    value={file.category}
                                    onValueChange={(value) =>
                                      updateFile(file.id, { category: value })
                                    }
                                  >
                                    <SelectTrigger className="h-10 md:h-8 text-base md:text-sm">
                                      <SelectValue placeholder="Select category" />
                                    </SelectTrigger>
                                    <SelectContent>
                                      <SelectItem value="before">
                                        Before Photos
                                      </SelectItem>
                                      <SelectItem value="progress">
                                        Progress Photos
                                      </SelectItem>
                                      <SelectItem value="after">
                                        After Photos
                                      </SelectItem>
                                      <SelectItem value="detail">
                                        Detail Shots
                                      </SelectItem>
                                      <SelectItem value="overview">
                                        Overview
                                      </SelectItem>
                                      <SelectItem value="walkthrough">
                                        Walkthrough
                                      </SelectItem>
                                    </SelectContent>
                                  </Select>
                                </div>
                              </div>

                              {/* Alt Text */}
                              <div>
                                <Label className="text-xs font-medium">
                                  Alt Text
                                </Label>
                                <Input
                                  value={file.altText}
                                  onChange={(e) =>
                                    updateFile(file.id, {
                                      altText: e.target.value,
                                    })
                                  }
                                  placeholder="Accessibility description for screen readers..."
                                  className="h-10 md:h-8 text-base md:text-sm"
                                />
                              </div>
                            </div>
                          )}

                          {/* Advanced Mode - All Fields */}
                          {editMode === "advanced" && (
                            <div className="space-y-4">
                              {/* File Name */}
                              <div>
                                <Label className="text-xs font-medium">
                                  File Name
                                </Label>
                                <Input
                                  value={file.fileName}
                                  onChange={(e) =>
                                    updateFile(file.id, {
                                      fileName: e.target.value,
                                    })
                                  }
                                  placeholder="Custom file name..."
                                  className="h-8 text-sm"
                                />
                              </div>

                              {/* Description */}
                              <div>
                                <Label className="text-xs font-medium">
                                  Description
                                </Label>
                                <Textarea
                                  value={file.description}
                                  onChange={(e) =>
                                    updateFile(file.id, {
                                      description: e.target.value,
                                    })
                                  }
                                  placeholder="Detailed description of the image/video..."
                                  rows={2}
                                  className="text-sm"
                                />
                              </div>

                              {/* Caption */}
                              <div>
                                <Label className="text-xs font-medium">
                                  Caption
                                </Label>
                                <Input
                                  value={file.caption}
                                  onChange={(e) =>
                                    updateFile(file.id, {
                                      caption: e.target.value,
                                    })
                                  }
                                  placeholder="Short caption for display..."
                                  className="h-8 text-sm"
                                />
                              </div>

                              {/* Core Metadata Grid */}
                              <div className="grid grid-cols-1 gap-3">
                                <div>
                                  <Label className="text-xs font-medium">
                                    Tags
                                  </Label>
                                  <SmartDropdownInput
                                    fieldName={DROPDOWN_FIELDS.PROJECT_KEYWORDS}
                                    value={file.tags}
                                    onChange={(value) =>
                                      updateFile(file.id, { tags: value })
                                    }
                                    placeholder="project tags"
                                    allowMultiple={true}
                                    separator=","
                                    className="h-10 md:h-8 text-base md:text-sm"
                                  />
                                </div>
                                <div>
                                  <Label className="text-xs font-medium">
                                    Keywords
                                  </Label>
                                  <Input
                                    value={file.keywords}
                                    onChange={(e) =>
                                      updateFile(file.id, {
                                        keywords: e.target.value,
                                      })
                                    }
                                    placeholder="SEO keywords"
                                    className="h-10 md:h-8 text-base md:text-sm"
                                  />
                                </div>
                                <div>
                                  <Label className="text-xs font-medium">
                                    Alt Text
                                  </Label>
                                  <Input
                                    value={file.altText}
                                    onChange={(e) =>
                                      updateFile(file.id, {
                                        altText: e.target.value,
                                      })
                                    }
                                    placeholder="Accessibility description"
                                    className="h-10 md:h-8 text-base md:text-sm"
                                  />
                                </div>
                              </div>

                              {/* Attribution */}
                              <div>
                                <Label className="text-xs font-medium">
                                  Attribution
                                </Label>
                                <Input
                                  value={file.attribution}
                                  onChange={(e) =>
                                    updateFile(file.id, {
                                      attribution: e.target.value,
                                    })
                                  }
                                  placeholder="Photo credit, copyright, or source attribution..."
                                  className="h-8 text-sm"
                                />
                              </div>

                              {/* EXIF Data Display & Edit */}
                              {file.exifData && (
                                <div className="bg-gray-50 p-3 rounded border">
                                  <Label className="text-xs font-medium text-gray-700 mb-2 block">
                                    EXIF Data
                                  </Label>
                                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
                                    <div>
                                      <span className="font-medium">
                                        Camera:
                                      </span>
                                      <Input
                                        value={file.exifData.camera || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              camera: e.target.value,
                                            },
                                          })
                                        }
                                        placeholder="Camera model"
                                        className="h-6 text-xs mt-1"
                                      />
                                    </div>
                                    <div>
                                      <span className="font-medium">Lens:</span>
                                      <Input
                                        value={file.exifData.lens || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              lens: e.target.value,
                                            },
                                          })
                                        }
                                        placeholder="Lens info"
                                        className="h-6 text-xs mt-1"
                                      />
                                    </div>
                                    <div>
                                      <span className="font-medium">ISO:</span>
                                      <Input
                                        value={file.exifData.iso || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              iso: e.target.value,
                                            },
                                          })
                                        }
                                        placeholder="ISO value"
                                        className="h-6 text-xs mt-1"
                                      />
                                    </div>
                                    <div>
                                      <span className="font-medium">Date:</span>
                                      <Input
                                        value={file.exifData.dateTaken || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              dateTaken: e.target.value,
                                            },
                                          })
                                        }
                                        placeholder="Date taken"
                                        className="h-6 text-xs mt-1"
                                      />
                                    </div>
                                  </div>
                                </div>
                              )}

                              {/* Structured Data Schema */}
                              <div className="bg-blue-50 p-3 rounded border border-blue-200">
                                <Label className="text-xs font-medium text-blue-900 mb-2 block">
                                  Structured Data (Schema.org)
                                </Label>
                                <div className="space-y-2">
                                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                                    <div>
                                      <Input
                                        value={
                                          file.structuredData?.creator || ""
                                        }
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            structuredData: {
                                              ...file.structuredData,
                                              creator: e.target.value,
                                            },
                                          })
                                        }
                                        placeholder="Creator/Author"
                                        className="h-7 text-xs"
                                      />
                                    </div>
                                    <div>
                                      <Input
                                        value={
                                          file.structuredData?.license || ""
                                        }
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            structuredData: {
                                              ...file.structuredData,
                                              license: e.target.value,
                                            },
                                          })
                                        }
                                        placeholder="License (e.g., CC BY 4.0)"
                                        className="h-7 text-xs"
                                      />
                                    </div>
                                  </div>
                                  <div className="text-xs text-blue-600">
                                    This data will be embedded as JSON-LD for
                                    SEO and rich snippets
                                  </div>
                                </div>
                              </div>
                            </div>
                          )}

                          {/* Complete Mode - All Fields with Full Control */}
                          {editMode === "complete" && (
                            <div className="space-y-4 border-l-4 border-purple-200 pl-4">
                              {/* File Management */}
                              <div className="bg-purple-50 p-3 rounded">
                                <h4 className="text-xs font-bold text-purple-900 mb-2">
                                  File Management
                                </h4>
                                <div className="grid grid-cols-1 gap-3">
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Original File Name
                                    </Label>
                                    <Input
                                      value={file.fileName}
                                      onChange={(e) =>
                                        updateFile(file.id, {
                                          fileName: e.target.value,
                                        })
                                      }
                                      className="h-7 text-xs"
                                    />
                                  </div>
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Display Title
                                    </Label>
                                    <Input
                                      value={file.title}
                                      onChange={(e) =>
                                        updateFile(file.id, {
                                          title: e.target.value,
                                        })
                                      }
                                      className="h-7 text-xs"
                                    />
                                  </div>
                                </div>
                              </div>

                              {/* Content Description */}
                              <div className="bg-blue-50 p-3 rounded">
                                <h4 className="text-xs font-bold text-blue-900 mb-2">
                                  Content Description
                                </h4>
                                <div className="space-y-2">
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Caption
                                    </Label>
                                    <Input
                                      value={file.caption}
                                      onChange={(e) =>
                                        updateFile(file.id, {
                                          caption: e.target.value,
                                        })
                                      }
                                      placeholder="Brief caption for display"
                                      className="h-7 text-xs"
                                    />
                                  </div>
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Description
                                    </Label>
                                    <Textarea
                                      value={file.description}
                                      onChange={(e) =>
                                        updateFile(file.id, {
                                          description: e.target.value,
                                        })
                                      }
                                      placeholder="Detailed description"
                                      rows={3}
                                      className="text-xs"
                                    />
                                  </div>
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Alt Text (Accessibility)
                                    </Label>
                                    <Input
                                      value={file.altText}
                                      onChange={(e) =>
                                        updateFile(file.id, {
                                          altText: e.target.value,
                                        })
                                      }
                                      placeholder="Screen reader description"
                                      className="h-7 text-xs"
                                    />
                                  </div>
                                </div>
                              </div>

                              {/* Classification */}
                              <div className="bg-green-50 p-3 rounded">
                                <h4 className="text-xs font-bold text-green-900 mb-2">
                                  Classification & Tagging
                                </h4>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Category
                                    </Label>
                                    <Select
                                      value={file.category}
                                      onValueChange={(value) =>
                                        updateFile(file.id, { category: value })
                                      }
                                    >
                                      <SelectTrigger className="h-7 text-xs">
                                        <SelectValue />
                                      </SelectTrigger>
                                      <SelectContent>
                                        <SelectItem value="before">
                                          Before Photos
                                        </SelectItem>
                                        <SelectItem value="progress">
                                          Progress Photos
                                        </SelectItem>
                                        <SelectItem value="after">
                                          After Photos
                                        </SelectItem>
                                        <SelectItem value="detail">
                                          Detail Shots
                                        </SelectItem>
                                        <SelectItem value="overview">
                                          Overview
                                        </SelectItem>
                                        <SelectItem value="walkthrough">
                                          Walkthrough
                                        </SelectItem>
                                        <SelectItem value="documentation">
                                          Documentation
                                        </SelectItem>
                                        <SelectItem value="reference">
                                          Reference
                                        </SelectItem>
                                      </SelectContent>
                                    </Select>
                                  </div>
                                  <div>
                                    <Label className="text-xs font-medium">
                                      Tags
                                    </Label>
                                    <SmartDropdownInput
                                      fieldName={
                                        DROPDOWN_FIELDS.PROJECT_KEYWORDS
                                      }
                                      value={file.tags}
                                      onChange={(value) =>
                                        updateFile(file.id, { tags: value })
                                      }
                                      allowMultiple={true}
                                      separator=","
                                      className="h-7 text-xs"
                                    />
                                  </div>
                                </div>
                                <div className="mt-2">
                                  <Label className="text-xs font-medium">
                                    SEO Keywords
                                  </Label>
                                  <Input
                                    value={file.keywords}
                                    onChange={(e) =>
                                      updateFile(file.id, {
                                        keywords: e.target.value,
                                      })
                                    }
                                    placeholder="SEO keywords, comma separated"
                                    className="h-7 text-xs"
                                  />
                                </div>
                              </div>

                              {/* Attribution & Rights */}
                              <div className="bg-orange-50 p-3 rounded">
                                <h4 className="text-xs font-bold text-orange-900 mb-2">
                                  Attribution & Rights
                                </h4>
                                <div>
                                  <Label className="text-xs font-medium">
                                    Attribution
                                  </Label>
                                  <Input
                                    value={file.attribution}
                                    onChange={(e) =>
                                      updateFile(file.id, {
                                        attribution: e.target.value,
                                      })
                                    }
                                    placeholder="Photo credit, copyright, or source attribution"
                                    className="h-7 text-xs"
                                  />
                                </div>
                              </div>

                              {/* Technical EXIF Data */}
                              {file.exifData && (
                                <div className="bg-gray-50 p-3 rounded">
                                  <h4 className="text-xs font-bold text-gray-900 mb-2">
                                    EXIF Technical Data
                                  </h4>
                                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                                    <div>
                                      <Label className="text-xs">Camera</Label>
                                      <Input
                                        value={file.exifData.camera || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              camera: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="Camera model"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">Lens</Label>
                                      <Input
                                        value={file.exifData.lens || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              lens: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="Lens info"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">
                                        Focal Length
                                      </Label>
                                      <Input
                                        value={file.exifData.focalLength || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              focalLength: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="mm"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">
                                        Aperture
                                      </Label>
                                      <Input
                                        value={file.exifData.aperture || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              aperture: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="f/2.8"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">
                                        Shutter Speed
                                      </Label>
                                      <Input
                                        value={file.exifData.shutterSpeed || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              shutterSpeed: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="1/60s"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">ISO</Label>
                                      <Input
                                        value={file.exifData.iso || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              iso: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="400"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">
                                        Date Taken
                                      </Label>
                                      <Input
                                        value={file.exifData.dateTaken || ""}
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              dateTaken: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="Date"
                                      />
                                    </div>
                                    <div>
                                      <Label className="text-xs">
                                        GPS Coordinates
                                      </Label>
                                      <Input
                                        value={
                                          file.exifData.gpsCoordinates || ""
                                        }
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            exifData: {
                                              ...file.exifData,
                                              gpsCoordinates: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="lat,lng"
                                      />
                                    </div>
                                  </div>
                                </div>
                              )}

                              {/* Structured Data Schema.org */}
                              <div className="bg-indigo-50 p-3 rounded">
                                <h4 className="text-xs font-bold text-indigo-900 mb-2">
                                  Structured Data (Schema.org)
                                </h4>
                                <div className="space-y-2">
                                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                                    <div>
                                      <Label className="text-xs">
                                        Schema Type
                                      </Label>
                                      <Select
                                        value={
                                          file.structuredData?.["@type"] || ""
                                        }
                                        onValueChange={(value) =>
                                          updateFile(file.id, {
                                            structuredData: {
                                              ...file.structuredData,
                                              "@type": value,
                                            },
                                          })
                                        }
                                      >
                                        <SelectTrigger className="h-6 text-xs">
                                          <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                          <SelectItem value="ImageObject">
                                            Image Object
                                          </SelectItem>
                                          <SelectItem value="VideoObject">
                                            Video Object
                                          </SelectItem>
                                          <SelectItem value="Photograph">
                                            Photograph
                                          </SelectItem>
                                          <SelectItem value="CreativeWork">
                                            Creative Work
                                          </SelectItem>
                                        </SelectContent>
                                      </Select>
                                    </div>
                                    <div>
                                      <Label className="text-xs">Creator</Label>
                                      <Input
                                        value={
                                          file.structuredData?.creator || ""
                                        }
                                        onChange={(e) =>
                                          updateFile(file.id, {
                                            structuredData: {
                                              ...file.structuredData,
                                              creator: e.target.value,
                                            },
                                          })
                                        }
                                        className="h-6 text-xs"
                                        placeholder="Creator name"
                                      />
                                    </div>
                                  </div>
                                  <div>
                                    <Label className="text-xs">License</Label>
                                    <Input
                                      value={file.structuredData?.license || ""}
                                      onChange={(e) =>
                                        updateFile(file.id, {
                                          structuredData: {
                                            ...file.structuredData,
                                            license: e.target.value,
                                          },
                                        })
                                      }
                                      className="h-6 text-xs"
                                      placeholder="e.g., CC BY 4.0, All Rights Reserved"
                                    />
                                  </div>
                                  <div className="text-xs text-indigo-600 bg-indigo-100 p-2 rounded">
                                    💡 This structured data will be embedded as
                                    JSON-LD for enhanced SEO, rich snippets, and
                                    better search engine understanding.
                                  </div>
                                </div>
                              </div>
                            </div>
                          )}

                          {/* AI Suggestions */}
                          {enableAIFeatures && file.autoGenerated && (
                            <div className="text-xs bg-blue-50 p-2 rounded border border-blue-200">
                              <div className="flex items-center gap-2 mb-1">
                                <Wand2 className="h-3 w-3 text-blue-600" />
                                <span className="font-medium text-blue-900">
                                  AI Suggestions Available
                                </span>
                              </div>
                              <div className="space-y-1 text-blue-700">
                                {file.autoGenerated.suggestedTags && (
                                  <p>
                                    <strong>Tags:</strong>{" "}
                                    {file.autoGenerated.suggestedTags.join(
                                      ", ",
                                    )}
                                  </p>
                                )}
                                {file.autoGenerated.aiDescription && (
                                  <p>
                                    <strong>AI Description:</strong>{" "}
                                    {file.autoGenerated.aiDescription}
                                  </p>
                                )}
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
