/**
 * Review requests from the phone. This module RECORDS a request; it does not
 * deliver one. Nothing here — and nothing behind it — sends a text or an
 * email:
 *
 * - the phone never sends. There is no messaging code in this app.
 * - the server's Twilio route exists but nothing in the product calls it for a
 *   review request, and no worker drains the table. A recorded row sits there
 *   until a person acts on it.
 * - the web dashboard's "send" is `window.open('sms:…')` / `mailto:` — it opens
 *   the operator's own messaging app on their own machine (see
 *   client/pages/AdminReviews.tsx, handleSendReviewRequest). A human sends it.
 *
 * So callers must say "recorded" / "waiting to be sent", never "sent". The one
 * honest same-second delivery this app has is the QR code: the customer is
 * standing there and scans it (see app/review-qr.tsx).
 *
 * Connected: inserts the same review_requests row the web dashboard lists.
 * Demo: a local record that shows up in the Reviews tab immediately.
 *
 * Three things the insert MUST get right:
 *
 * - `.select('id')` — the id is generated by the database and it is the whole
 *   address of the review page (`/review/:id`). Throwing it away meant every
 *   request created here was unreachable; a QR code printed from a thrown-away
 *   id is a dead link on a customer's counter.
 * - `business_id` — the web ReviewGate loads branding only when the row has a
 *   business_id (see client/pages/ReviewGate.tsx). Without it the page falls
 *   through to whatever `business_settings` happens to be cached in that
 *   browser's localStorage, i.e. a different company's name and logo shown to
 *   your customer. We refuse to create a request we cannot attribute rather
 *   than create one that misrepresents someone.
 * - `status` — this used to be written as 'pending', which is in nobody's
 *   vocabulary: the phone's reader maps unknown statuses to 'sent' (lib/data.ts)
 *   so the Reviews tab showed a "Sent" badge for a message that was never sent,
 *   and the web dashboard's tab filters only allow sent/viewed/completed/
 *   expired/scheduled, so the row was invisible there — unsendable as well as
 *   mislabelled. A request nobody has delivered is written as 'scheduled': it
 *   reads "Scheduled" on both clients and lands in the web dashboard's
 *   Scheduled tab, which is the screen that can actually send it.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';

import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import type { Job, ReviewRequest } from '@/lib/types';
import { workspace } from '@/lib/workspace';

const STORAGE_KEY = 'lsr-review-requests-v1';
const APP_URL = (process.env.EXPO_PUBLIC_APP_URL ?? '').trim();

/**
 * One sentence, in one place, for every screen that offers to create a review
 * request. If this app ever gains a real sending path, this string is what has
 * to change — not a dozen screens that each guessed.
 */
export const REVIEW_DELIVERY_NOTE =
  'The app records the request and can turn it into a QR code the customer scans on the spot. It does not text or email anyone — a recorded request waits under Scheduled until someone sends it from the web dashboard.';

export interface SendReviewInput {
  customerName: string;
  phone: string;
  channel: 'sms' | 'email';
  /**
   * Handed over in person (QR code) instead of delivered. The row is still
   * created — the customer needs a link to scan — but no contact detail is
   * required and nothing is queued for sending.
   */
  inPerson?: boolean;
}

export interface SendReviewResult {
  /** The review_requests row id — exactly what `/review/:id` needs. */
  id?: string;
  /** 'local' ids exist only on this device and will not open on the web gate. */
  scope?: 'remote' | 'local';
  /**
   * False when the row was created without a business_id (the column is not on
   * this database yet), so the review page cannot load your branding. Callers
   * that show the link to a customer must say so.
   */
  businessLinked?: boolean;
  error?: string;
}

/**
 * Base URL of the deployed web app, or null when it is not configured.
 *
 * Deliberately no fallback domain: this URL gets printed onto QR codes and
 * handed to customers, and a guessed hostname is a scannable link to a site we
 * do not control. Callers must treat null as "cannot show a link".
 */
export function reviewBaseUrl(): string | null {
  if (!APP_URL) return null;
  const trimmed = APP_URL.replace(/\/+$/, '');
  return /^https?:\/\/[^\s/]+$/i.test(trimmed) ? trimmed : null;
}

/** Public review-gate URL for a request id, or null when no base URL is set. */
export function reviewUrl(requestId: string): string | null {
  const base = reviewBaseUrl();
  if (!base || !requestId) return null;
  return `${base}/review/${encodeURIComponent(requestId)}`;
}

export async function getLocalReviewRequests(): Promise<ReviewRequest[]> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as ReviewRequest[]) : [];
  } catch {
    return [];
  }
}

/** True when the failure is "that column isn't on this database", not a real rejection. */
function isMissingColumn(message: string): boolean {
  return /business_id/i.test(message) && /(does not exist|could not find|schema cache)/i.test(message);
}

/**
 * True when the database refused the status value itself (a CHECK constraint or
 * an enum that predates the web app's vocabulary), as opposed to refusing the
 * row. The table isn't defined in this repo, so we cannot know which values it
 * accepts — we ask for the honest one and fall back rather than fail the user.
 */
function isRejectedStatus(message: string): boolean {
  return /status/i.test(message) && /(check constraint|invalid input value|violates)/i.test(message);
}

/**
 * Creates (does NOT send) a review request. See the module header: no code path
 * in this product delivers the message. `id` comes back so the caller can show
 * the QR code, which is the one way a customer gets the link from the phone.
 *
 * Named `sendReviewRequest` only because app/review-request/[id].tsx imports it
 * under that name; it records.
 */
export async function sendReviewRequest(
  job: Job,
  input: SendReviewInput,
): Promise<SendReviewResult> {
  const record: ReviewRequest = {
    id: `rr-local-${Date.now()}`,
    customer_name: input.customerName.trim() || job.client_name,
    contact: input.phone.trim(),
    channel: input.channel,
    // A QR code is handed to the customer on the spot, so 'sent' is literally
    // true for it. Everything else is only recorded — nothing in this app sends
    // it — so it stays 'scheduled' ("waiting to go out"), which is the closest
    // honest word ReviewRequestStatus has.
    status: input.inPerson ? 'sent' : 'scheduled',
    sent_at: new Date().toISOString(),
    job_title: job.title,
  };

  if (isSupabaseConfigured) {
    const business = await workspace.getCurrent().catch(() => null);
    // Demo ids are not uuids and belong to no real company, so they are as
    // useless to the review page as no business at all.
    const businessId = business && !business.id.startsWith('demo') ? business.id : null;
    if (!businessId) {
      // Better to refuse than to file a request nobody can attribute: the
      // review page would then fall back to whatever branding is cached in the
      // customer's browser, which can be a different company entirely.
      return {
        error: business
          ? `“${business.name}” is the sample workspace, so a review request filed under it would show the wrong company to your customer. Switch to your real business in Settings first.`
          : "Your business hasn't loaded, so this request can't be filed against it — and a request with no business shows the wrong company on the review page. Try again in a moment.",
      };
    }

    const base = {
      customer_name: record.customer_name,
      // Sent verbatim (empty string, not null) — unchanged from before, so a
      // NOT NULL customer_phone keeps behaving the way it does today.
      customer_phone: record.contact,
      project_name: job.title,
      // The column is named sent_at but is really "created"; the web dashboard
      // sorts and dates rows by it, and it may be NOT NULL, so it is still
      // written. The status is what tells anyone whether it went out.
      sent_at: record.sent_at,
    };

    try {
      const attempt = async (status: string) => {
        let linked = true;
        let res = await supabase
          .from('review_requests')
          .insert({ ...base, status, business_id: businessId })
          .select('id')
          .single();

        if (res.error && isMissingColumn(res.error.message)) {
          // Older database: the column isn't there yet. Still create the request
          // (that is today's behaviour) but tell the caller it is unbranded.
          linked = false;
          res = await supabase
            .from('review_requests')
            .insert({ ...base, status })
            .select('id')
            .single();
        }
        return { res, linked };
      };

      // 'scheduled' is what puts the row in the web dashboard's Scheduled tab,
      // the only screen with a "Send Now" action. If this database restricts the
      // column to older values we fall back to 'pending' rather than lose the
      // request — the phone's copy says "recorded, not sent" either way.
      let { res: result, linked: businessLinked } = await attempt(record.status);
      if (result.error && isRejectedStatus(result.error.message)) {
        ({ res: result, linked: businessLinked } = await attempt('pending'));
      }

      if (result.error) return { error: result.error.message };

      const id = result.data?.id ? String(result.data.id) : '';
      if (!id) {
        return { error: 'The request was saved but the server did not return its id.' };
      }
      return { id, scope: 'remote', businessLinked };
    } catch (error) {
      return { error: error instanceof Error ? error.message : 'Could not save the request.' };
    }
  }

  // Demo mode: persist locally so the Reviews tab reflects it. The id is a
  // local string — the web review page cannot resolve it, and callers are told
  // via scope: 'local' so they can say so instead of printing a dead link.
  const existing = await getLocalReviewRequests();
  await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify([record, ...existing])).catch(
    () => undefined,
  );
  return { id: record.id, scope: 'local', businessLinked: false };
}
